---
- name: install yum centos 7 epel
  yum:
    name: https://mirrors.aliyun.com/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install deps
  yum: name={{ item }} state=latest
  with_items:
    - gcc
    - gcc-c++
    - gd
    - cmake
    - patch
    - autoconf
    - libjpeg
    - libjpeg-devel
    - libpng
    - libpng-devel
    - freetype
    - libxml2-devel
    - zlib
    - zlib-devel
    - glibc
    - glibc-devel
    - glib2
    - glib2-devel
    - ncurses
    - ncurses-devel
    - curl
    - curl-devel
    - e2fsprogs
    - krb5-devel
    - libidn
    - libidn-devel
    - openssl
    - openldap-devel
    - nss_ldap
    - openldap-clients
    - openldap-servers
    - pcre-devel
    - libmcrypt-devel
